---
title: "A protocol for systematically reviewing traditional Chinese medicine meta-analyses where the translation “modified” is used"
author: "Rong Guang"
date: "`r Sys.Date()`"
output:
  bookdown::pdf_document2:
    latex_engine: lualatex
---

A protocol for systematically reviewing traditional Chinese medicine meta-analyses where the translation “modified” is used

Abstract: (263 words excluding the keywords, please note that the section of results is neither possible nor required in a protocol)
Background
Borrowing established terminologies from modern medicine is a common practice in writing English-medium reports on meta-analyses for traditional Chinese medicine (TCM). If proper clarification about some key translations is not accompanied in the reports, readers’ perceived reliability of the evidence might inflate. An example is the term “加减”. It is often translated into “modified” for “clarity”, yet at the cost of fidelity. Clarifying this translation is important to unbiasedly delivering the meta-analytical evidence to international readers. Yet, there is no evidence if this is sufficiently done.

Aims
We aim to justify the concern over the practice of borrowing established terminologies without sufficient clarification when writing English-medium reports on TCM meta-analyses, and to report a protocol allowing to systematically review TCM meta-analyses analyses where “modified” was used to translate “加减”. 

Methods (Note that )
We plan to retrieve all TCM meta-analyses involving modified formula published throughout 2018 to 2022. Two independent reviewers will screen titles and abstracts, include relevant full text articles, extract data from the studies, and evaluate the prevalent practices in clarifying the borrowed term “modified”. The data extracted will be used to estimate the prevalent practice in clarifying the term “modified”. 

Discussion
The systematic review based on the current protocol will assesses the practice of clarifying the term “modified” in TCM meta-analyses involving modified formula. The finding will inform 
international readers/peer-reviewers of a. the validity of published TCM meta-analyses; b. if inflated quality of TCM meta-analytical evidence is a concern, practically. The systematic review will be crucial for understanding the quality of published TCM meta-analyses.

Key words: Traditional Chinese medicine; meta-analysis; modified formula; insufficient translation of terminology; protocol 

